version: '3'
services: 
    zookeeper: 
        container_name: zookeeper
        image: bitnami/zookeeper:latest
        networks: 
            mall:
                aliases:
                    - zk
        ports: 
            - "2181:2181"
        volumes:
            - ./zookeeper_cluster/zookeeper1/conf:/opt/bitnami/zookeeper/conf
            - ./zookeeper_cluster/zookeeper1/data:/opt/bitnami/zookeeper/data
            - ./zookeeper_cluster/zookeeper1/datalog:/opt/bitnami/zookeeper/log
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    zookeeper1:
        image: 'bitnami/zookeeper:latest'
        ports:
            - '2181'
            - '2888'
            - '3888'
        volumes:
            - /zookeeper_cluster/zookeeper-persistence:/bitnami/zookeeper
        environment:
            - ZOO_SERVER_ID=1
            - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
            - ALLOW_ANONYMOUS_LOGIN=yes
    zookeeper2:
        image: 'bitnami/zookeeper:latest'
        ports:
            - '2181'
            - '2888'
            - '3888'
        volumes:
            - /zookeeper_cluster/zookeeper-persistence:/bitnami/zookeeper
        environment:
            - ZOO_SERVER_ID=2
            - ZOO_SERVERS=zookeeper1:2888:3888,0.0.0.0:2888:3888,zookeeper3:2888:3888
            - ALLOW_ANONYMOUS_LOGIN=yes
    zookeeper3:
        image: 'bitnami/zookeeper:latest'
        ports:
            - '2181'
            - '2888'
            - '3888'
        volumes:
            - /zookeeper_cluster/zookeeper-persistence:/bitnami/zookeeper
        environment:
            - ZOO_SERVER_ID=3
            - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,0.0.0.0:2888:3888
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka: 
        container_name: kafka
        image: wurstmeister/kafka
        networks: 
            - mall
        ports: 
            - "9092:9092"
        depends_on: 
            - zookeeper
        environment: 
            KAFKA_ADVERTISED_HOST_NAME: 192.168.50.126
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_ZOOKEEPER_CONNECT: zk:2181
    redis:
        container_name: redis
        image: redis
        networks: 
            - mall
        ports: 
            - "6379:6379"
    mysql:
        container_name: mysql
        image: mysql
        networks: 
            mall:
                aliases:
                    - mysqldb1
        ports: 
            - "3306:3306"
        restart: always                       
        volumes:
            - ./mysql/data/:/var/lib/mysql/                             #映射mysql的数据目录到宿主机，保存数据
        environment: 
            MYSQL_ROOT_PASSWORD: root
    tomcat:
        container_name: tomcat
        restart: always
        image: tomcat
        networks: 
            mall:
                aliases:
                    - tomcat1
        ports:
          - 8080:8080
          - 8009:8009
        volumes:
          - ./tomcat/logs/:/usr/local/tomcat/logs/
                                                     #连接数据库镜像
          
    nginx:
        container_name: nginx
        restart: always
        image: nginx
        networks: 
            - mall
        ports:
          - 80:80
          - 443:443
          - 5050:5050
          - 4040:4040
        volumes:
          - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf            #映射nginx的配置文件到容器里
          - ./nginx/logs/:/var/log/nginx/
          - ./nginx/data/:/var/share/nginx/html/                     #映射nginx的网页目录到容器里
 
networks:
  mall:
        