version: '3'
services: 
    zookeeper1:
        image: 'bitnami/zookeeper:latest'
        networks: 
            mall:
                aliases:
                    - zookeeper1
        ports:
            - "12181:2181"
        volumes:
            - ./zookeeper_cluster/zookeeper-persistence1:/bitnami/zookeeper
        environment:
            - ZOO_SERVER_ID=1
            - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
            - ALLOW_ANONYMOUS_LOGIN=yes
    zookeeper2:
        image: 'bitnami/zookeeper:latest'
        networks: 
            mall:
                aliases:
                    - zookeeper2
        ports:
            - "22181:2181"
        volumes:
            - ./zookeeper_cluster/zookeeper-persistence2:/bitnami/zookeeper
        environment:
            - ZOO_SERVER_ID=2
            - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
            - ALLOW_ANONYMOUS_LOGIN=yes
    zookeeper3:
        image: 'bitnami/zookeeper:latest'
        networks: 
            mall:
                aliases:
                    - zookeeper2
        ports:
            - "32181:2181"
        volumes:
            - ./zookeeper_cluster/zookeeper-persistence3:/bitnami/zookeeper
        environment:
            - ZOO_SERVER_ID=3
            - ZOO_SERVERS=zookeeper1:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka1: 
        container_name: kafka1
        image: wurstmeister/kafka
        networks: 
            - mall
        ports: 
            - "19092:9092"
            - "19999:9999"
        depends_on: 
            - zookeeper1
            - zookeeper2
            - zookeeper3
        environment: 
            JMX_PORT: "9999"
            KAFKA_ADVERTISED_HOST_NAME: "kafka1"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
            KAFKA_BROKER_ID: "1"
    kafka2: 
        container_name: kafka2
        image: wurstmeister/kafka
        networks: 
            - mall
        ports: 
            - "29092:9092"
            - "29999:9999"
        depends_on: 
            - zookeeper1
            - zookeeper2
            - zookeeper3
        environment: 
            JMX_PORT: "9999"
            KAFKA_ADVERTISED_HOST_NAME: "kafka2"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
            KAFKA_BROKER_ID: "2"
    kafka3: 
        container_name: kafka3
        image: wurstmeister/kafka
        networks: 
            - mall
        ports: 
            - "39092:9092"
            - "39999:9999"
        depends_on: 
            - zookeeper1
            - zookeeper2
            - zookeeper3
        environment: 
            JMX_PORT: "9999"
            KAFKA_ADVERTISED_HOST_NAME: "kafka3"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
            KAFKA_BROKER_ID: "3"
    redis:
        container_name: redis
        image: redis
        networks: 
            - mall
        ports: 
            - "6379:6379"
    mysql:
        container_name: mysql
        image: mysql
        networks: 
            mall:
                aliases:
                    - mysqldb1
        ports: 
            - "3306:3306"
        restart: always                       
        volumes:
            - ./mysql/data/:/var/lib/mysql/                             #映射mysql的数据目录到宿主机，保存数据
        environment: 
            MYSQL_ROOT_PASSWORD: root
    tomcat:
        container_name: tomcat
        restart: always
        image: tomcat
        networks: 
            mall:
                aliases:
                    - tomcat1
        ports:
          - 8080:8080
          - 8009:8009
        volumes:
          - ./tomcat/logs/:/usr/local/tomcat/logs/
                                                     #连接数据库镜像
          
    nginx:
        container_name: nginx
        restart: always
        image: nginx
        networks: 
            - mall
        ports:
          - 80:80
          - 443:443
          - 5050:5050
          - 4040:4040
        volumes:
          - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf            #映射nginx的配置文件到容器里
          - ./nginx/logs/:/var/log/nginx/
          - ./nginx/data/:/var/share/nginx/html/                     #映射nginx的网页目录到容器里
 
networks:
  mall:
        